### ISSUE TITLE
freehdl fails to build on Yosemite 10.10.1, XCode 6.1.1

### ISSUE THREAD

**Issue by ralphrmartin** [guitorri/homebrew-tap#4]
$ brew install freehdl
==> Installing freehdl from guitorri/homebrew-tap
==> Downloading http://sourceforge.net/projects/qucs/files/qucs/0.0.16/freehdl-0.0.8.tar.gz
Already downloaded: /Library/Caches/Homebrew/freehdl-0.0.8.tar.gz
==> Patching
patching file freehdl/freehdl-config
==> ./configure --prefix=/usr/local/Cellar/freehdl/0.0.8
==> make install
libtool: compile:  g++-4.9 -DPACKAGE_NAME=\"freehdl\" -DPACKAGE_TARNAME=\"freehdl\" -DPACKAGE_VERSION=\"0.0.8\" "-DPACKAGE_STRING=\"freehdl 0.0.8\"" -DPACKAGE_BUGREPORT=\"edwin@ds.e-technik.uni-dortmund.de\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DYYTEXT_POINTER=1 -DHAVE_FLEXLEXER_H=1 -DHAVE_EXECINFO_H=1 -DHAVE_GETOPT_H=1 -DSIZEOF_INT=4 -DHAVE_VASPRINTF=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_SOCKET=1 -DHAVE_GETTIMEOFDAY=1 -I. -I.. -I.. -g -O2 -c persistent_cdfg_dump.cc -o libfreehdl_kernel_la-persistent_cdfg_dump.o >/dev/null 2>&1
libtool: compile:  g++-4.9 -DPACKAGE_NAME=\"freehdl\" -DPACKAGE_TARNAME=\"freehdl\" -DPACKAGE_VERSION=\"0.0.8\" "-DPACKAGE_STRING=\"freehdl 0.0.8\"" -DPACKAGE_BUGREPORT=\"edwin@ds.e-technik.uni-dortmund.de\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DYYTEXT_POINTER=1 -DHAVE_FLEXLEXER_H=1 -DHAVE_EXECINFO_H=1 -DHAVE_GETOPT_H=1 -DSIZEOF_INT=4 -DHAVE_VASPRINTF=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_SOCKET=1 -DHAVE_GETTIMEOFDAY=1 -I. -I.. -I.. -g -O2 -c signal_source_list_array.cc -o libfreehdl_kernel_la-signal_source_list_array.o >/dev/null 2>&1
libtool: compile:  g++-4.9 -DPACKAGE_NAME=\"freehdl\" -DPACKAGE_TARNAME=\"freehdl\" -DPACKAGE_VERSION=\"0.0.8\" "-DPACKAGE_STRING=\"freehdl 0.0.8\"" -DPACKAGE_BUGREPORT=\"edwin@ds.e-technik.uni-dortmund.de\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DYYTEXT_POINTER=1 -DHAVE_FLEXLEXER_H=1 -DHAVE_EXECINFO_H=1 -DHAVE_GETOPT_H=1 -DSIZEOF_INT=4 -DHAVE_VASPRINTF=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_SOCKET=1 -DHAVE_GETTIMEOFDAY=1 -I. -I.. -I.. -g -O2 -c kernel_class.cc -o libfreehdl_kernel_la-kernel_class.o >/dev/null 2>&1
libtool: compile:  g++-4.9 -DPACKAGE_NAME=\"freehdl\" -DPACKAGE_TARNAME=\"freehdl\" -DPACKAGE_VERSION=\"0.0.8\" "-DPACKAGE_STRING=\"freehdl 0.0.8\"" -DPACKAGE_BUGREPORT=\"edwin@ds.e-technik.uni-dortmund.de\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DYYTEXT_POINTER=1 -DHAVE_FLEXLEXER_H=1 -DHAVE_EXECINFO_H=1 -DHAVE_GETOPT_H=1 -DSIZEOF_INT=4 -DHAVE_VASPRINTF=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_SOCKET=1 -DHAVE_GETTIMEOFDAY=1 -I. -I.. -I.. -g -O2 -c register.cc -o libfreehdl_kernel_la-register.o >/dev/null 2>&1
make: *** [install-recursive] Error 1

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/guitorri/homebrew-tap/issues

**Comment by mkeller0815** [comment]
It also fails on 10.9.5 with XCode 6.2. I needed to install gcc view homebrew to even start building freehdl, but it fails with gcc5 installed. 
Here's the output:

libtool: compile:  g++-5 -DPACKAGE_NAME=\"freehdl\" -DPACKAGE_TARNAME=\"freehdl\" -DPACKAGE_VERSION=\"0.0.8\" "-DPACKAGE_STRING=\"freehdl 0.0.8\"" -DPACKAGE_BUGREPORT=\"edwin@ds.e-technik.uni-dortmund.de\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DYYTEXT_POINTER=1 -DHAVE_FLEXLEXER_H=1 -DHAVE_EXECINFO_H=1 -DHAVE_GETOPT_H=1 -DSIZEOF_INT=4 -DHAVE_VASPRINTF=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_SOCKET=1 -DHAVE_GETTIMEOFDAY=1 -I. -I.. -I.. -g -O2 -c pcounter.cc  -fno-common -DPIC -o .libs/libfreehdl_kernel_la-pcounter.o
libtool: compile:  g++-5 -DPACKAGE_NAME=\"freehdl\" -DPACKAGE_TARNAME=\"freehdl\" -DPACKAGE_VERSION=\"0.0.8\" "-DPACKAGE_STRING=\"freehdl 0.0.8\"" -DPACKAGE_BUGREPORT=\"edwin@ds.e-technik.uni-dortmund.de\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DYYTEXT_POINTER=1 -DHAVE_FLEXLEXER_H=1 -DHAVE_EXECINFO_H=1 -DHAVE_GETOPT_H=1 -DSIZEOF_INT=4 -DHAVE_VASPRINTF=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_SOCKET=1 -DHAVE_GETTIMEOFDAY=1 -I. -I.. -I.. -g -O2 -c pcounter.cc -o libfreehdl_kernel_la-pcounter.o >/dev/null 2>&1
libtool: compile:  g++-5 -DPACKAGE_NAME=\"freehdl\" -DPACKAGE_TARNAME=\"freehdl\" -DPACKAGE_VERSION=\"0.0.8\" "-DPACKAGE_STRING=\"freehdl 0.0.8\"" -DPACKAGE_BUGREPORT=\"edwin@ds.e-technik.uni-dortmund.de\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DYYTEXT_POINTER=1 -DHAVE_FLEXLEXER_H=1 -DHAVE_EXECINFO_H=1 -DHAVE_GETOPT_H=1 -DSIZEOF_INT=4 -DHAVE_VASPRINTF=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_SOCKET=1 -DHAVE_GETTIMEOFDAY=1 -I. -I.. -I.. -g -O2 -c db.cc -o libfreehdl_kernel_la-db.o >/dev/null 2>&1
fhdl_stream.cc: In member function 'fhdl_ostream_t& fhdl_ostream_t::operator<<(char*)':
fhdl_stream.cc:69:28: error: 'strlen' was not declared in this scope
       write(fd, p, strlen(p) + 1);
                            ^
make[1]: *** [libfreehdl_kernel_la-fhdl_stream.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: compile:  g++-5 -DPACKAGE_NAME=\"freehdl\" -DPACKAGE_TARNAME=\"freehdl\" -DPACKAGE_VERSION=\"0.0.8\" "-DPACKAGE_STRING=\"freehdl 0.0.8\"" -DPACKAGE_BUGREPORT=\"edwin@ds.e-technik.uni-dortmund.de\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DYYTEXT_POINTER=1 -DHAVE_FLEXLEXER_H=1 -DHAVE_EXECINFO_H=1 -DHAVE_GETOPT_H=1 -DSIZEOF_INT=4 -DHAVE_VASPRINTF=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_SOCKET=1 -DHAVE_GETTIMEOFDAY=1 -I. -I.. -I.. -g -O2 -c persistent_cdfg_dump.cc -o libfreehdl_kernel_la-persistent_cdfg_dump.o >/dev/null 2>&1
libtool: compile:  g++-5 -DPACKAGE_NAME=\"freehdl\" -DPACKAGE_TARNAME=\"freehdl\" -DPACKAGE_VERSION=\"0.0.8\" "-DPACKAGE_STRING=\"freehdl 0.0.8\"" -DPACKAGE_BUGREPORT=\"edwin@ds.e-technik.uni-dortmund.de\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DYYTEXT_POINTER=1 -DHAVE_FLEXLEXER_H=1 -DHAVE_EXECINFO_H=1 -DHAVE_GETOPT_H=1 -DSIZEOF_INT=4 -DHAVE_VASPRINTF=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_SOCKET=1 -DHAVE_GETTIMEOFDAY=1 -I. -I.. -I.. -g -O2 -c register.cc -o libfreehdl_kernel_la-register.o >/dev/null 2>&1
make: *** [install-recursive] Error 1
==> Formula
Tap: guitorri/homebrew-tap
Path: /usr/local/Library/Taps/guitorri/homebrew-tap/freehdl.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 681b438398f028eaf00c644bc4a8df64435a937a
Last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit ivybridge
OS X: 10.9.5-x86_64
Xcode: 6.2
CLT: N/A
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.7.0_67
==> ENV
HOMEBREW_CC: gcc-5
HOMEBREW_CXX: g++-5
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/bison:/usr/local/opt/flex:/usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/apache2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.9
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
ACLOCAL_PATH: /usr/local/opt/bison/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/bison/bin:/usr/local/opt/flex/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/gcc/bin

**Comment by guitorri** [comment]
The issue is that freehdl is abandoned updstream and I won't have the time to patch it right now. If you need a VDHL compiler I suggest you take a look at GHDL. They provide installers for Mac.

**Comment by mkeller0815** [comment]
Thanks for the quick reply. Is there an easy way to integrate GHDL into QUCS? I just need a tool for simulating digital circuits but I don't want to go too deep into any "development" task. If there's an easy way, good. If not I'll looking for an other simulator.

**Comment by guitorri** [comment]
Please update and try again. I believe it was just a missing headers.
If other formulas fail, try to install them without gcc-5.
This worked for me:
```
brew unlink libtool && brew install libtool # was failing to update under gcc-5
HOMEBREW_CC=gcc-5 HOMEBREW_CXX=g++-5 brew install freehdl
```
I am still on OS X 10.9.5, it should work for you.

We want/need to replace freehdl by GHDL on the Qucs project, but development work is needed. Not sure how hard or when it will take place.

**Comment by mkeller0815** [comment]
Many thanks,
it works. Even with Yosemite. I just installed gcc 5 and relinked the libtool. After that I could build freehdl and run an digital simulation. 
My current version of Yosemite is 10.10.3
Mario.
