### ISSUE TITLE
Warning: calling Formula.sha1 is deprecated

### ISSUE THREAD

**Issue by jmaibaum** [guitorri/homebrew-tap#5]
Hi,

for some days I get the following warnings while updating your tap:

    Warning: Calling Formula.sha1 is deprecated!
    Use Formula.sha256 instead.
    /usr/local/Library/Taps/guitorri/homebrew-tap/adms.rb:6:in `<class:Adms>'
    Please report this to the guitorri/tap tap!

    Warning: Calling SoftwareSpec#sha1 is deprecated!
    Use SoftwareSpec#sha256 instead.
    /usr/local/Library/Taps/guitorri/homebrew-tap/adms.rb:6:in `<class:Adms>'
    Please report this to the guitorri/tap tap!

    Warning: Calling Resource#sha1 is deprecated!
    Use Resource#sha256 instead.
    /usr/local/Library/Taps/guitorri/homebrew-tap/adms.rb:6:in `<class:Adms>'
    Please report this to the guitorri/tap tap!

Plus the same warnings for all other software that I have installed from your tap.

Thanks for your effort in making qucs available for Homebrew!

Best,
Johannes

**Comment by guitorri** [comment]
Hi. Thank you for the feedback. I updated to sha256. It should be fixed now.
